version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    network: host
    environment:
      - OPENAI_API_KEY
      - OPENAI_API_HOST	
      - OPENAI_API_TYPE
      - OPENAI_API_VERSION
      - AZURE_DEPLOYMENT_ID
      - OPENAI_ORGANIZATION	
      - DEFAULT_MODEL
      - NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT
      - NEXT_PUBLIC_DEFAULT_TEMPERATURE	
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - GITHUB_ID
      - GITHUB_SECRET
      - LOGIN_REQUIRED
      - APP_NAME
      - API_ENTRYPOINT
      - PRIVATE_API_ENTRYPOINT
      - WORKSPACES_ENDPOINT
      - DATABASE_URL
      - GOOGLE_API_KEY
      - GOOGLE_CSE_ID
      - GUEST_CODE
      - API_BASE_URL
      - NEXT_PUBLIC_LOGIN_REQUIRED
      - LOG_INCOMING_MESSAGES
      - LOG_TRIM_MESSAGES
