version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 8443:8443
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - NEXT_PUBLIC_AZURE_AD_CLIENT_ID=${NEXT_PUBLIC_AZURE_AD_CLIENT_ID}
      - NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET=${NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET}
      - NEXT_PUBLIC_AZURE_AD_TENANT_ID=${NEXT_PUBLIC_AZURE_AD_TENANT_ID}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DEFAULT_MODEL=${DEFAULT_MODEL}