apiVersion: v1
kind: Namespace
metadata:
  name: jarvis-client
---
apiVersion: v1
kind: Secret
metadata:
  namespace: jarvis-client
  name: jarvis-client
type: Opaque
data:
  JARVISAI_API_HOST: <base64 encoded host>
  JARVISAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jarvis-client
  name: jarvis-client
  labels:
    app: jarvis-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jarvis-client
  template:
    metadata:
      labels:
        app: jarvis-client
    spec:
      containers:
        - name: jarvis-client
          image: <docker user>/jarvis-client:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: JARVISAI_API_HOST
              valueFrom:
                secretKeyRef:
                  name: jarvis-client
                  key: JARVISAI_API_HOST
            - name: JARVISAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jarvis-client
                  key: JARVISAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: jarvis-client
  name: jarvis-client
  labels:
    app: jarvis-client
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: jarvis-client
  type: ClusterIP
