apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: chatgpt-ui
type: Opaque
data:
  OPENAI_API_KEY: <GPT API KEY> 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: chatgpt-ui
  labels:
    app: chatgpt-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-ui
  template:
    metadata:
      labels:
        app: chatgpt-ui
    spec:
      containers:
        - name: chatgpt-ui
          image: registry.digitalocean.com/francisco/chatgpt-ui:202304300116
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatgpt-ui
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: chatgpt-ui-svc
  labels:
    app: chatgpt-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: chatgpt-ui
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatgpt-ui-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: ai.sakurain.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatgpt-ui-svc
            port:
              number: 80
