name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_test_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build, Test and Deploy Job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      # Only Needed for Testing
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Update settings in staticwebapp.config.json
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'staticwebapp.config.json'
        env:
          AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}

      - name: SWA Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_FOREST_0DD60B40F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: ".next" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          app_build_command: "npm run build" # Build command - optional
          api_build_command: "rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache" # Api build command - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_FOREST_0DD60B40F }}
          app_location: "/"
          action: "close"