# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbot-ziyi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ziyiregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ea396e96b16c44c28aace98cf53a34f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e2a36c592d71408691a1e01d2945cabd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ziyiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea396e96b16c44c28aace98cf53a34f7 }}/chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbot-ziyi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4903962a125944ec84e69d888d92ae03 }}
        images: 'ziyiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea396e96b16c44c28aace98cf53a34f7 }}/chatbot:${{ github.sha }}'